#!/usr/bin/env bash
# setup_map.sh — Meta-Agent-Protocol 装载脚手架
# 将 MAP 规范自动装载到宿主仓库根目录。
# Usage: bash conventions/scripts/setup_map.sh
#
# 行为:
#   1. 检测是否通过 git submodule 引入
#   2. 从 templates/ 生成 AI_RULES.md, .aider.conf.yml, .importlinter
#   3. 用 <<<PLACEHOLDER>>> 标记需要宿主自定义的部分
#   4. 不覆盖宿主已有文件（除非 --force）

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAP_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOST_ROOT="$(cd "$MAP_ROOT/.." && pwd)"

FORCE=false
if [[ "${1:-}" == "--force" ]]; then
    FORCE=true
fi

# ─── Banner ───
echo ""
echo "  ╔══════════════════════════════════════════════╗"
echo "  ║  Meta-Agent-Protocol (MAP) — Bootstrapper   ║"
echo "  ║  v1.0.0                                     ║"
echo "  ╚══════════════════════════════════════════════╝"
echo ""
echo "  MAP root : $MAP_ROOT"
echo "  Host root: $HOST_ROOT"
echo ""

# ─── Pre-flight checks ───
if [ ! -d "$MAP_ROOT/templates" ]; then
    echo "❌ ERROR: MAP templates/ directory not found at $MAP_ROOT/templates"
    echo "   Is MAP properly installed as a git submodule?"
    exit 1
fi

if [ ! -d "$HOST_ROOT/.git" ]; then
    echo "⚠️  WARNING: $HOST_ROOT does not appear to be a git repository."
    echo "   setup_map.sh should be run from a git repo root that includes MAP as a submodule."
fi

# ─── Check submodule status ───
cd "$HOST_ROOT"
if git submodule status 2>/dev/null | grep -q "conventions"; then
    echo "✅ MAP detected as git submodule 'conventions'"
else
    echo "⚠️  MAP not detected as git submodule 'conventions'"
    echo "   Expected: git submodule add <MAP_URL> conventions"
    echo "   Continuing anyway (manual installation mode)..."
fi

# ─── Helper: generate file from template ───
generate_file() {
    local template="$1"
    local target="$2"
    local description="$3"

    if [ -f "$target" ] && [ "$FORCE" != true ]; then
        echo "⏭️  SKIP: $target already exists. Use --force to overwrite."
        return 0
    fi

    cp "$template" "$target"
    echo "✅ CREATED: $target — $description"
}

# ─── Generate AI_RULES.md ───
generate_file \
    "$MAP_ROOT/templates/AI_RULES.md.template" \
    "$HOST_ROOT/AI_RULES.md" \
    "Global Agent behavior constitution (9 laws)"

# ─── Generate .aider.conf.yml ───
generate_file \
    "$MAP_ROOT/templates/aider.conf.yml.template" \
    "$HOST_ROOT/.aider.conf.yml" \
    "Aider global configuration"

# ─── Generate .importlinter ───
generate_file \
    "$MAP_ROOT/templates/importlinter.ini.template" \
    "$HOST_ROOT/.importlinter" \
    "Import-linter architecture firewall configuration"

# ─── Generate delegate_to_aider.sh (from agent-loop.md §7) ───
DELEGATE_TARGET="$HOST_ROOT/delegate_to_aider.sh"
if [ -f "$DELEGATE_TARGET" ] && [ "$FORCE" != true ]; then
    echo "⏭️  SKIP: $DELEGATE_TARGET already exists."
else
    cat > "$DELEGATE_TARGET" << 'DELEGATE_SCRIPT'
#!/usr/bin/env bash
# delegate_to_aider.sh — Architect → Executor delegation bridge
# Generated by Meta-Agent-Protocol (MAP) setup_map.sh
set -euo pipefail

TASK_FILE="${1:-}"
if [ -z "$TASK_FILE" ] || [ ! -f "$TASK_FILE" ]; then
    echo "Usage: ./delegate_to_aider.sh <task_file> [target_files...]"
    echo ""
    echo "  task_file:    Path to a task description file (see MAP rules/agent-loop.md §2)"
    echo "  target_files: Files Aider is allowed to modify"
    exit 1
fi
shift
TARGET_FILES="${@:-}"

echo "🚀 Delegating to Aider..."
echo "   Task: $(head -1 "$TASK_FILE")"
echo "   Files: ${TARGET_FILES:-auto-detect}"

TASK_CONTENT=$(cat "$TASK_FILE")
aider --model deepseek/deepseek-v4-pro \
      --message "$TASK_CONTENT" \
      ${TARGET_FILES} \
      2>&1 | tee /tmp/aider_$(date +%Y%m%d_%H%M%S).log

echo ""
echo "📋 Git diff summary:"
git diff --stat
DELEGATE_SCRIPT
    chmod +x "$DELEGATE_TARGET"
    echo "✅ CREATED: $DELEGATE_TARGET — Architect → Executor delegation bridge"
fi

# ─── Done ───
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  MAP bootstrap complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Next steps:"
echo "  1. Edit AI_RULES.md — fill in {{PLACEHOLDER}} markers:"
echo "     - {{TEST_COMMANDS}} — test commands per sub-project"
echo "     - {{REDLINE_EXTRA}} — additional red-line files (if any)"
echo "     - {{TEST_TARGETS}} — make targets for test-all"
echo "     - {{PRD_PATH_MAP}} — PRD document path per sub-project"
echo "     - {{LOCAL_CONVENTIONS_SUMMARY}} — one-line constraint per sub-project"
echo ""
echo "  2. Edit .aider.conf.yml — fill in {{PLACEHOLDER}} markers:"
echo "     - {{WORKSPACE_NAME}}"
echo "     - {{PRD_DOC_MAP}}"
echo "     - {{ROADMAP_PATH_MAP}}"
echo "     - {{PRD_PATH_MAP}}"
echo ""
echo "  3. Edit .importlinter — fill in {{PLACEHOLDER}} markers:"
echo "     - {{PACKAGE_LIST}}"
echo "     - {{MODULE_LIST}}"
echo "     - {{IGNORE_IMPORTS}}"
echo "     - {{LAYER_LIST}}"
echo ""
echo "  4. Create WORKSPACE_MAP.md (your global coordinate system)"
echo ""
echo "  5. Create Makefile with test-<project> targets and test-all"
echo ""
echo "  6. Commit: git add -A && git commit -m 'feat: bootstrap MAP v1.0.0'"
echo ""
